#= require_self
#= require_tree ./templates
#= require_tree ./models
#= require_tree ./views
#= require_tree ./routers
window.CShopping.Models= {}
window.CShopping.Collections= {}
window.CShopping.Routers= {}
window.CShopping.Views= {}